name: GitHub Actions Cache Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get RoR2 version id
      id: ror2-version
      run: echo "::set-output name=ver::$(curl -s https://api.steamcmd.net/v1/info/1180760 | jq -r ".data.\"1180760\".depots.branches.public.buildid")"

    - name: Cache RoR2
      id: cache-ror2
      uses: actions/cache@v2
      with:
        path: ror2
        key: ${{ steps.ror2-version.outputs.ver }}

    - name: Download RoR2
      if: steps.cache-ror2.outputs.cache-hit != 'true'
      run: ./download-ror2.sh
      
    - name: Checkout AssetsPathDumper
      uses: actions/checkout@v2
      with:
        repository: KingEnderBrine/AssetsPathDumper
        path: './AssetsPathDumper'
      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 6.0.x
    - run: |
        cd ./AssetsPathDumper/AssetsPathDumper/
        dotnet run --configuration Release ../../ror2/
        
    - name: Prepare git commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        mv "./AssetsPathDumper/AssetsPathDumper/bin/Release/net6.0/assetPathsDump.html" "./assetPathsDump.html"
        git add "./assetPathsDump.html"
        git commit -m "Add html"
    - name: Push html to repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
