name: GitHub Actions Cache Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache RoR2
      id: cache-ror2
      uses: actions/cache@v2
      with:
        path: ror2
        key: ${{ runner.os }}-${{ hashFiles('**/*.dll') }}

    - name: Download RoR2
      if: steps.cache-ror2.outputs.cache-hit != 'true'
      run: /download-ror2.sh

    - name: Generate Resources Path Webpage
      run: /generate-resources-path-webpage.sh
