name: GitHub Actions Cache Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get RoR2 version id
      id: ror2-version
      run: echo "::set-output name=ver::$(curl -s https://api.steamcmd.net/v1/info/1180760 | jq -r ".data.\"1180760\".depots.branches.public.buildid")"

    - name: Cache RoR2
      id: cache-ror2
      uses: actions/cache@v2
      with:
        path: ror2
        key: ${{ steps.ror2-version.outputs.ver }}

    - name: Download RoR2
      if: steps.cache-ror2.outputs.cache-hit != 'true'
      run: ./download-ror2.sh

    - name: Generate Resources Path Webpage
      run: ./generate-resources-path-webpage.sh
